#--- spring
spring:
  profiles:
    active: local

#--- jpa
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

#--- datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: test
    password: test1234

#--- logging
logging:
  config: classpath:log.xml


#--- kafka
kafka:
  broker:
    address: localhost:9092
    group-id: test-kafka
  zookeeper:
    connect: localhost:2181